name: Run Jakarta Data TCK

on:
  schedule:
    - cron: '0 0 * * 1,3,5' #Monday, Wednesday, Friday at Midnight

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java-version: [17, 21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Running Jakarta Data TCK tests
        run: mvn test --file jnosql-data-tck-runner/pom.xml -Djakarta.tck.profile=standalone -Djnosql.document.database=jnosql -Djnosql.mongodb.host=localhost:27017
